apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 12-sealedsecrets
  namespace: kube-system
spec:
  project: default
  source:
    repoURL: https://github.com/chrisshiels/kubernetes.git
    targetRevision: HEAD
    path: kustomize/12-sealedsecrets/local
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
