apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 50-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chrisshiels/kubernetes.git
    targetRevision: HEAD
    path: kustomize/50-monitoring/local
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
