apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 70-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chrisshiels/kubernetes.git
    targetRevision: HEAD
    path: kustomize/70-application/local
  destination:
    server: https://kubernetes.default.svc
    namespace: application
