---
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    storage:
      deleteClaim: true
      size: 10Gi
      type: persistent-claim
      class: longhorn-onereplica
  zookeeper:
    replicas: 3
    storage:
      deleteClaim: true
      size: 10Gi
      type: persistent-claim
      deleteClaim: false
      class: longhorn-onereplica
