---
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 2.7.0
    replicas: 3
    config:
      log.message.format.version: "2.7"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    storage:
      type: persistent-claim
      class: longhorn-onereplica
      size: 5Gi
      deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: longhorn-onereplica
      size: 5Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
  cruiseControl: {}

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: user
  labels:
    strimzi.io/cluster: kafka

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.7.0
  replicas: 3
  bootstrapServers: kafka-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-status
