apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
#commonLabels:
#  app.kubernetes.io/instance: 50-monitoring
bases:
- ../stock
resources:
- namespace.yaml
patches:
- patch.yaml
