apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 40-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chrisshiels/kubernetes.git
    targetRevision: HEAD
    path: kustomize/40-argocd/local
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
