apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 65-elastic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chrisshiels/kubernetes.git
    targetRevision: HEAD
    path: kustomize/65-elastic/local
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
