apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
commonLabels:
  app.kubernetes.io/instance: 15-metallb
bases:
- ../all
resources:
- configmap.yaml
- secret.yaml
