---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/instance: 20-ingress-nginx
spec:
  replicas: 3

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: ingress-nginx-controller
#  namespace: ingress-nginx
#  labels:
#    app.kubernetes.io/instance: 20-ingress-nginx
#spec:
#  ports:
#  - name: http
#    port: 80
#    nodePort: 30080
#  - name: https
#    port: 443
#    nodePort: 30443

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/instance: 20-ingress-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.121.121
