# See:
# https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-users-and-roles.html
#
# host$ mkdir filerealm
# host$ touch filerealm/users filerealm/users_roles
#
# host$ sudo docker run \
#         --rm \
#         -v $(pwd)/filerealm:/usr/share/elasticsearch/config \
#         docker.elastic.co/elasticsearch/elasticsearch:7.12.0 \
#         bin/elasticsearch-users useradd fluentd -p fluentd -r superuser
#
# host$ kubectl -n application \
#         create secret --dry-run=client \
#                 generic filerealm --from-file ./filerealm -o yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: filerealm
data:
  users: Zmx1ZW50ZDokMmEkMTAkNmZpL2FHakhXaEFDNVgvSE5FZEhsLkVMVmNYYjBzTzVWSDJPNG03TjBUTWk5ZXBqUy9xL1cK
  users_roles: c3VwZXJ1c2VyOmZsdWVudGQK

---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: application
spec:
  version: 7.12.0
  auth:
    fileRealm:
    - secretName: filerealm
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  rules:
  - host: elastic.local
    http:
      paths:
      - backend:
          service:
            name: application-es-http
            port:
              name: https
        path: /
        pathType: ImplementationSpecific

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: application
spec:
  version: 7.12.0
  count: 3
  elasticsearchRef:
    name: application

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  rules:
  - host: kibana.local
    http:
      paths:
      - backend:
          service:
            name: application-kb-http
            port:
              name: https
        path: /
        pathType: ImplementationSpecific
