---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-test
  namespace: monitoring
data:
  run.sh: |-
    @test "Test Health" {
      # Fix pod prometheus-grafana-test erroring.
      sleep 30
      url="http://prometheus-grafana/api/health"

      code=$(wget --server-response --spider --timeout 10 --tries 1 ${url} 2>&1 | awk '/^  HTTP/{print $2}')
      [ "$code" == "200" ]
    }
