---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-onereplica
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  dataLocality: best-effort
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
