# Fix:
# 'StatefulSet volumeclaimtemplates added when base did not include it #504.'
# https://github.com/kubernetes-sigs/kustomize/issues/504
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  volumeClaimTemplates: []
