apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app.kubernetes.io/instance: 80-argocd
bases:
- ../stock
resources:
- ingress.yaml
- namespace.yaml
#patchesJson6902:
#- target:
#    kind: Service
#    name: argocd-server
#  patch: |-
#    - op: replace
#      path: /spec/type
#      value: NodePort
#images:
#- name: argoproj/argocd
#  newName: quay.io/argoproj/argocd
#- name: redis
#  newName: quay.io/bitnami/redis
#  newTag: '6.2'
