apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
#commonLabels:
#  app.kubernetes.io/instance: 80-argocd
bases:
- ../stock
resources:
- namespace.yaml
patches:
- patch.yaml
