---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: 80-argocd
  name: argocd
  namespace: argocd


---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: 80-argocd
  name: applications.argoproj.io
  namespace: argocd

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: 80-argocd
  name: appprojects.argoproj.io
  namespace: argocd
