apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-system
commonLabels:
  app.kubernetes.io/instance: 65-kafka
bases:
- ../stock
resources:
- namespace.yaml
- clusterrolebindings.yaml
patchesStrategicMerge:
- patch.yaml
