apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: kafka-system
spec:
  template:
    spec:
      containers:
      - name: strimzi-cluster-operator
        env:
        - name: STRIMZI_NAMESPACE
          $patch: delete
        - name: STRIMZI_NAMESPACE
          value: '*'
